<?php
$breakpoint = true;
?>
<div id="prxgt_dwnl_dcp">
    <app-root>Loading...</app-root>
    <script type="text/javascript" src="/dcp/inline.bundle.js"></script>
    <!-- MOBI-730: disable Angular 'defulne' -->
    <!--    <script type="text/javascript" src="/dcp/scripts.bundle.js"></script>-->
    <script type="text/javascript" src="/dcp/vendor.bundle.js"></script>
    <script type="text/javascript" src="/dcp/main.bundle.js"></script>
</div>