<?php
/** @var \Praxigento\Downline\Block\Dcp $block */
$isDevMode = $block->isDevMode();
?>
<div id="prxgt_dwnl_dcp" style="min-height: 840px;">
    <app-root>Loading...</app-root>
    <!-- MOBI-730, MOBI-1064 -->
    <?php if ($isDevMode): ?>
        <!-- DEV MODE resources -->
        <script type="text/javascript" src="/dcp/inline.bundle.js"></script>
        <script type="text/javascript" src="/dcp/styles.bundle.js"></script>
        <script type="text/javascript" src="/dcp/vendor.bundle.js"></script>
        <script type="text/javascript" src="/dcp/main.bundle.js"></script>
    <?php else: ?>
        <!-- PROD MODE resources -->
        <script type="text/javascript" src="/dcp/<?php $block->outInline() ?>"></script>
        <script type="text/javascript" src="/dcp/<?php $block->outScripts() ?>"></script>
        <script type="text/javascript" src="/dcp/<?php $block->outMain() ?>"></script>
    <?php endif; ?>
</div>