<?php
/** @var \Praxigento\Downline\Block\Customer\Account\Reflink $block */
?>
<div class="block">
    <div>
        <span class="label"><?= $block->escapeHtml(__('Parent MLM ID')) ?>:</span>
        <span class="value"><?= $block->getMlmIdParent() ?></span>
    </div>
    <div>
        <span class="label"><?= $block->escapeHtml(__('Own MLM ID')) ?>:</span>
        <span class="value"><?= $block->getMlmIdOwn() ?></span>
    </div>
    <div>
        <span class="label"><?= $block->escapeHtml(__('Referral Code')) ?>:</span>
        <span class="value"><?= $block->getReferralCode() ?></span>
    </div>
    <div>
        <span class="label"><?= $block->escapeHtml(__('Referral Link')) ?>:</span>
        <span class="value"><a href="<?= $block->getReferralLink() ?>"><?= $block->getReferralLink() ?></a></span>
    </div>
</div>
